### PR TITLE
The council (seznamka Chads) will decide your fate ️‍🔥️‍

### PR DESCRIPTION
**Pull request by jirkavrba**

### CODE REVIEW

**Comment by SoptikHa2** [comment]
We, as a community, need this

**Review by MartinKolarik — DISMISSED** [review]

**Comment by jirkavrba** [comment]
@tenhobi

**Review by MartinKolarik — APPROVED** [review]
LGTM

**Review by pokorj54 — APPROVED** [review]
Seems ok

**Comment by jirkavrba** [comment]
No merge?

**Comment by pokorj54** [comment]
https://media.giphy.com/media/fu8pNDmOpBk8T2sjMu/giphy.gif

**Comment by stepech** [comment]
I can bet you'll regret this soon enough.

**Comment by tenhobi** [comment]
🤦‍♂️

**Pull request merged**
