### PR TITLE
Make checklist syntax consistent with Markdown

### PR DESCRIPTION
**Pull request by albertmoravec**
Make the checked item syntax consistent with GitHub flavored Markdown

### CODE REVIEW

**Review by stepech — APPROVED** [review]

**Comment by stepech** [comment]
@tenhobi can you please assign this correct label? Not sure under what category this falls.

**Comment by stepech** [comment]
:+1: :heart:

**Comment by tenhobi** [comment]
Well, some people use ❌ (`:x:`) to mark not finished tasks, ergo markdown-like syntax might be confusing.

**Comment by stepech** [comment]
@albertmoravec can we merge? (We usually leave that up to the PR author)

**Review by tenhobi — DISMISSED** [review]
> Well, some people use ❌ (`:x:`) to mark not finished tasks, ergo markdown-like syntax might be confusing.

We can discuss some possibilities (or change to this convention) on Discord with people who use it.

**Pull request merged**
