### PR TITLE
Added M0dEx birthday reminder, because we all love him <3

### PR DESCRIPTION
**Pull request by SoptikHa2**
To @M0dEx with love <3

### CODE REVIEW

**Review by MartinKolarik — DISMISSED** [review]

**Review by stepech — DISMISSED** [review]
Nope

**Review by Bertik23 — DISMISSED** [review]

**Review by tenhobi — DISMISSED** [review]

**Comment by ostorc** [comment]
Not really sure, but we have disabled merging into the dev, until someone finishes his/her semestral work

**Comment by stepech** [comment]
Ok, I think we have an issue here. We can not just stop the whole bot development  just because some developer greenhorn doesn't have some work for completely different subject.

**Comment by ostorc** [comment]
Not funny anymore.

**Pull request closed without merging**
