### PR TITLE
Rewrite polls, introduce Add command to modify existing Abc polls

### LINKED ISSUE #51: Edit poll
Creator of the poll should be able to add extra answers to the poll.

```.polladd <link> another answer```

I think that other modification should not be possible, because it could change the meaning of the poll.

### PR DESCRIPTION
**Pull request by stepech**
Done and tested...

implements #51 
and much more...

Changed basically whole code behind polls. They are no longer hidden behind interface, but they have new abstraction layer on top. Makes it much easier to introduce new poll types in the future (maybe checklist for volleyball, some seasonal themes, or just poll where Botner doesn't remove extra reactions), also, most of the code is in one place now.
Extra reactions are now being removed to be ready in case user wants to add option later. This includes YesNo polls (for now) just to make it consistent, but can be removed in a matter of seconds.
Maybe in the future, we can go for polls compeltely independent on code and moved into config? With options like `removeExcessReactions`, `allowOptionsAddingAfterSend`, and list of default reactions... idk

I know there are code smells, like having strings like "AbcPoll" right in code, but I just don't know C# enough to know how to avoid it without iporting configs everywhere. If that'd be prefered, I'll do it. If you have some better idea - with enums or idk.. Please.

### CODE REVIEW

**Comment by stepech** [comment]
Should I rewrite poll handler to run asynchronously? Issue is I then cant't return correct handler propagation. Either always return Continue, or always Stop, even if the reaction is deleted.

**Comment by stepech** [comment]
Exploring built in library poll function

**Comment by tenhobi** [comment]
Will test tomorrow.

**Review by tenhobi — DISMISSED** [review]
Very cool!

**Comment by tenhobi** [comment]
@stepech ready to merge or you wanna update something?

**Comment by stepech** [comment]
Done and dusted 👍

**Review by tenhobi — APPROVED** [review]
.

**Pull request merged**
